# Site settings 配置站点
title: 'Picc0lo'
description: '昵称比克，喜欢星星，后端开发者/假装极客/PC装机发烧友/实验室设备供应商，热爱技术。'
keyword: 'dave的独立博客, 比克工作室（Picc0lo STudios，PST）,后端技术栈,Java/C++/Python'
url: 'picc0lo.top' # your host
encoding: UTF-8
# when build blog on server, if you don't need baseurl, you should leave this value blank.
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# if you're using GitHub Pages, set baseurl to your blog's .
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''



# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2020

# Author 配置博主信息
author: 'Yun Chou'
nickname: '比克'
bio: '后端开发者，热爱技术&星星'
avatar: '/assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['qq','wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: '//yushan2025@gmail.com'
  facebook: '//facebook.com/Yun.chou.865'
  linkedin: '//linkedin.com/in/dave-yun-z-88a54a152/'
  github: '//github.com/dendyikbc'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 17 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 5
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
